import { Character, CharacterPassive } from '../../types';

const BASE_PASSIVE: CharacterPassive = {
  description: '',
  maxHealthBonus: 0,
  maxShieldBonus: 0,
  startingShield: 0,
  speedMult: 1,
  damageMult: 1,
  damageResistance: 0,
  reloadMult: 1,
  killHealAmount: 0,
  materialsBonus: 0,
};

// portraitSource: swap null → require('../../../assets/portraits/vex.png') once images are added
export const CHARACTERS: Character[] = [
  {
    id: 'vex',
    name: 'Vex "Glitch" Calder',
    title: 'The Phantom',
    lore: 'Quantum systems engineer who learned to weaponize lag. Blinks in and out of reality like a bad signal.',
    meteorQuip: 'I felt that before it landed. I hate this.',
    portraitSource: null,
    accentColor: '#aa44ff',
    passive: {
      ...BASE_PASSIVE,
      description: 'Unstable signal. +10% movement speed and 25% faster reloads.',
      speedMult: 1.1,
      reloadMult: 0.75,
    },
    ability: {
      name: 'Phase Skip',
      description: 'Teleports forward 250 units and leaves a decoy echo at the origin.',
      cooldownMs: 14000,
      durationMs: 0,
      effectType: 'none',
    },
  },
  {
    id: 'brutus',
    name: 'Brutus Hale',
    title: 'The Wall',
    lore: 'Walked through a building collapse once. The building lost.',
    meteorQuip: 'Good. Something to hit back.',
    portraitSource: null,
    accentColor: '#888888',
    passive: {
      ...BASE_PASSIVE,
      description: 'Ironclad frame. +80 max HP.',
      maxHealthBonus: 80,
    },
    ability: {
      name: 'Titan Guard',
      description: 'Deploys a frontal energy shield, absorbing all incoming damage for 6 seconds before releasing it as a shockwave.',
      cooldownMs: 28000,
      durationMs: 6000,
      effectType: 'damage_immunity',
    },
  },
  {
    id: 'nyra',
    name: 'Nyra Solis',
    title: 'The Solar',
    lore: 'Channelled solar energy into her biology. Warm to the touch. Lethal at range.',
    meteorQuip: 'A core. Finally. Stay back — it\'s mine.',
    portraitSource: null,
    accentColor: '#ffaa00',
    passive: {
      ...BASE_PASSIVE,
      description: 'Solar resilience. Starts each match with 75 shield.',
      startingShield: 75,
    },
    ability: {
      name: 'Solar Bloom',
      description: 'Emits a healing flare — instantly restores 60 HP — while enemies within range are marked for +40% bonus damage for 5 seconds.',
      cooldownMs: 22000,
      durationMs: 5000,
      effectType: 'damage_boost',
    },
  },
  {
    id: 'kade',
    name: 'Kade "Lockjaw" Mercer',
    title: 'The Tracker',
    lore: 'Never loses a mark. Patience measured in days. Mercy measured in zero.',
    meteorQuip: 'Sky just did my job for me.',
    portraitSource: null,
    accentColor: '#cc6633',
    passive: {
      ...BASE_PASSIVE,
      description: 'Efficient hunter. Each elimination restores 15 HP.',
      killHealAmount: 15,
    },
    ability: {
      name: 'Trapline',
      description: 'Activates hidden snares — marks all enemies and increases outgoing damage by 40% for 6 seconds.',
      cooldownMs: 18000,
      durationMs: 6000,
      effectType: 'damage_boost',
    },
  },
  {
    id: 'iris',
    name: 'Iris Venn',
    title: 'The Fracture',
    lore: 'Psy-ops operator. Convinced three people they were somewhere else simultaneously.',
    meteorQuip: 'Controlled impact. Someone aimed that.',
    portraitSource: null,
    accentColor: '#cc44aa',
    passive: {
      ...BASE_PASSIVE,
      description: 'Misdirection mastery. 15% of all incoming damage is deflected.',
      damageResistance: 0.15,
    },
    ability: {
      name: 'Mind Fracture',
      description: 'Deploys hallucinations — enemies cannot accurately target for 4 seconds, effectively granting damage immunity.',
      cooldownMs: 20000,
      durationMs: 4000,
      effectType: 'damage_immunity',
    },
  },
  {
    id: 'rook',
    name: 'Rook Ashfall',
    title: 'The Smoke',
    lore: 'Tactical specialist. Controls terrain. The smoke is never random.',
    meteorQuip: 'New cover. Adapt.',
    portraitSource: null,
    accentColor: '#446688',
    passive: {
      ...BASE_PASSIVE,
      description: 'Prepared entry. +20 max HP and +20 max shield.',
      maxHealthBonus: 20,
      maxShieldBonus: 20,
    },
    ability: {
      name: 'Smoke Reign',
      description: 'Blankets the area — grants damage immunity for 3 seconds and doubles movement speed within the smoke.',
      cooldownMs: 16000,
      durationMs: 3000,
      effectType: 'damage_immunity',
    },
  },
  {
    id: 'talon',
    name: 'Talon Rhee',
    title: 'The Predator',
    lore: 'Apex hunter from a collapsed nation. Tracks by sound. Closes in silence.',
    meteorQuip: 'Flushed them right out. Efficient.',
    portraitSource: null,
    accentColor: '#882222',
    passive: {
      ...BASE_PASSIVE,
      description: 'Predator instinct. All weapons deal +15% damage.',
      damageMult: 1.15,
    },
    ability: {
      name: 'Predator Leap',
      description: 'Launches forward 200 units and marks the target, increasing all damage dealt to them by 50% for 5 seconds.',
      cooldownMs: 15000,
      durationMs: 5000,
      effectType: 'damage_boost',
    },
  },
  {
    id: 'voss',
    name: 'Dr. Quillan "Pulse" Voss',
    title: 'The Surgeon',
    lore: 'Field surgeon who operates on himself between engagements. The stitches are self-dissolving.',
    meteorQuip: 'Triage priority just changed.',
    portraitSource: null,
    accentColor: '#4488ff',
    passive: {
      ...BASE_PASSIVE,
      description: 'Biological optimization. +25 max HP and starts with 50 shield.',
      maxHealthBonus: 25,
      startingShield: 50,
    },
    ability: {
      name: 'Bio Surge',
      description: 'Sends a restorative wave — instantly heals 80 HP.',
      cooldownMs: 20000,
      durationMs: 0,
      effectType: 'none',
    },
  },
  {
    id: 'sable',
    name: 'Sable Korr',
    title: 'The Tether',
    lore: 'Former intelligence broker. Knows that information shared is pain shared.',
    meteorQuip: 'Accelerated evolution. The weak are being selected out.',
    portraitSource: null,
    accentColor: '#9933cc',
    passive: {
      ...BASE_PASSIVE,
      description: 'Precision focus. Weapon reloads 20% faster.',
      reloadMult: 0.8,
    },
    ability: {
      name: 'Shadow Bind',
      description: 'Tethers enemies — damage dealt to any target is increased by 45% for 5 seconds as the bind amplifies all hits.',
      cooldownMs: 18000,
      durationMs: 5000,
      effectType: 'damage_boost',
    },
  },
  {
    id: 'orin',
    name: 'Orin "Scrap" Dax',
    title: 'The Salvager',
    lore: 'Built his first weapon from a vending machine and a door hinge. Still uses it.',
    meteorQuip: 'Free parts. I\'ll take it.',
    portraitSource: null,
    accentColor: '#cc8800',
    passive: {
      ...BASE_PASSIVE,
      description: 'Resource specialist. Starts with triple building materials.',
      materialsBonus: 200,
    },
    ability: {
      name: 'Junk Fortress',
      description: 'Scavenges nearby debris — instantly grants +100 of each building material.',
      cooldownMs: 15000,
      durationMs: 0,
      effectType: 'none',
    },
  },
  {
    id: 'lyric',
    name: 'Lyric Vale',
    title: 'The Resonance',
    lore: 'Sound engineer turned soldier. The blast radius is calculated, not accidental.',
    meteorQuip: 'Beautiful resonance. Terrible timing.',
    portraitSource: null,
    accentColor: '#44ccaa',
    passive: {
      ...BASE_PASSIVE,
      description: 'Sonic amplification. All weapons deal +20% damage.',
      damageMult: 1.2,
    },
    ability: {
      name: 'Sonic Crescendo',
      description: 'Charges a focused sound blast — knocks back nearby enemies and deals +50% weapon damage for 5 seconds.',
      cooldownMs: 20000,
      durationMs: 5000,
      effectType: 'damage_boost',
    },
  },
  {
    id: 'magnus',
    name: 'Magnus Drift',
    title: 'The Gravity',
    lore: 'Physicist who discovered the practical applications of his research. Immediately regretted it.',
    meteorQuip: 'This is my fault. Again.',
    portraitSource: null,
    accentColor: '#6644ff',
    passive: {
      ...BASE_PASSIVE,
      description: 'Gravitational mass. +25% weapon damage, -10% movement speed.',
      damageMult: 1.25,
      speedMult: 0.9,
    },
    ability: {
      name: 'Gravity Well',
      description: 'Pulls enemies toward a central point — all pulled targets take +50% weapon damage for 5 seconds.',
      cooldownMs: 22000,
      durationMs: 5000,
      effectType: 'damage_boost',
    },
  },
  {
    id: 'eira',
    name: 'Eira Frost',
    title: 'The Glacier',
    lore: 'Cryogenic containment specialist. The "containment" part is optional.',
    meteorQuip: 'Heat. I despise heat.',
    portraitSource: null,
    accentColor: '#44ddff',
    passive: {
      ...BASE_PASSIVE,
      description: 'Ice armor. 20% of all incoming damage is deflected.',
      damageResistance: 0.2,
    },
    ability: {
      name: 'Cryo Veil',
      description: 'Freezes the surrounding ground — grants damage immunity for 4 seconds and creates ice barriers that block bullets.',
      cooldownMs: 20000,
      durationMs: 4000,
      effectType: 'damage_immunity',
    },
  },
  {
    id: 'jax',
    name: 'Jax "Overclock" Renn',
    title: 'The Overclocked',
    lore: 'Neural augmentations pushed past rated limits. The tremor in his hands is from the speed, not the fear.',
    meteorQuip: 'HA. Let\'s go again.',
    portraitSource: null,
    accentColor: '#ff4400',
    passive: {
      ...BASE_PASSIVE,
      description: 'Overclocked systems. +25% movement speed.',
      speedMult: 1.25,
    },
    ability: {
      name: 'Adrenal Override',
      description: 'Pushes all systems past the limit — doubles fire rate and movement speed for 5 seconds, but drains 5 HP per second during the effect.',
      cooldownMs: 20000,
      durationMs: 5000,
      effectType: 'rapid_fire',
    },
  },
  {
    id: 'kael',
    name: 'Kael Umbra',
    title: 'The Void',
    lore: 'Emerged from a void experiment intact. Mostly. The parts that changed are the useful parts.',
    meteorQuip: 'The void remembers this energy.',
    portraitSource: null,
    accentColor: '#220044',
    passive: {
      ...BASE_PASSIVE,
      description: 'Void-touched. 15% damage resistance and 20% faster reloads.',
      damageResistance: 0.15,
      reloadMult: 0.8,
    },
    ability: {
      name: 'Void Step',
      description: 'Becomes intangible for 5 seconds — grants damage immunity and passes through all obstacles.',
      cooldownMs: 25000,
      durationMs: 5000,
      effectType: 'damage_immunity',
    },
  },
];

export function getCharacter(id: string): Character {
  return CHARACTERS.find((c) => c.id === id) ?? CHARACTERS[0];
}

export const DEFAULT_CHARACTER_ID = CHARACTERS[0].id;
